<script>
setTimeout("document.location='session_refresh.php'",60000);
</script>
<?php
ini_set('session.use_cookies','1');
ini_set('session.use_trans_sid','0');
include("../../sc_conf/sc_session");
session_start();
?>
